### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by albsquadri** [danyaal/mandelbrot#1]
Dear developer,
I have tried to run your code but unfortunately I had problems. I open and just  run your script "mandelbrot.py" in Spyder and I have received the following message: "NameError: name 'xrange' is not defined". What was my mistake?
Thank you,
Antonio Squadri

**Comment by zhaipro** [comment]
Change the `xrange` to `range`.

https://github.com/zhaipro/mandelbrot/commit/9e935b820d70a9424f68d9572bb1a7b71e02e035

**Comment by danyaal** [comment]
resolved in the latest push to `master` (see https://github.com/danyaal/mandelbrot/commit/1f2d936cf58781fdea57acc28ba3d31be0e7e4fc)
